package com.star.people.mapper;

import com.star.people.model.AdminLoginInfo;
import com.star.people.model.AdminLoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int countByExample(AdminLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int deleteByExample(AdminLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int insert(AdminLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int insertSelective(AdminLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    List<AdminLoginInfo> selectByExample(AdminLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    AdminLoginInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") AdminLoginInfo record, @Param("example") AdminLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int updateByExample(@Param("record") AdminLoginInfo record, @Param("example") AdminLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int updateByPrimaryKeySelective(AdminLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_admin_login_info
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    int updateByPrimaryKey(AdminLoginInfo record);
}