package com.star.people.model;

import java.util.Date;

public class AdminLoginInfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.id
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.name
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.role
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.password
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.salt
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.addtime
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_admin_login_info.updatetime
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.id
     *
     * @return the value of pt_admin_login_info.id
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.id
     *
     * @param id the value for pt_admin_login_info.id
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.name
     *
     * @return the value of pt_admin_login_info.name
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.name
     *
     * @param name the value for pt_admin_login_info.name
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.role
     *
     * @return the value of pt_admin_login_info.role
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.role
     *
     * @param role the value for pt_admin_login_info.role
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.password
     *
     * @return the value of pt_admin_login_info.password
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.password
     *
     * @param password the value for pt_admin_login_info.password
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.salt
     *
     * @return the value of pt_admin_login_info.salt
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.salt
     *
     * @param salt the value for pt_admin_login_info.salt
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.addtime
     *
     * @return the value of pt_admin_login_info.addtime
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.addtime
     *
     * @param addtime the value for pt_admin_login_info.addtime
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_admin_login_info.updatetime
     *
     * @return the value of pt_admin_login_info.updatetime
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_admin_login_info.updatetime
     *
     * @param updatetime the value for pt_admin_login_info.updatetime
     *
     * @mbggenerated Sun Dec 27 17:41:32 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}